In [54]:
from scipy.io import arff
import numpy as np
from sklearn.metrics import balanced_accuracy_score

f = open('data/kin8nm.arff', 'r', encoding='utf-8')
data, meta = arff.loadarff(f)
data

array([(-0.015119,  0.360741,  0.469398,  1.309675,  0.988024, -0.025493,  0.664071,  0.062763, b'P'),
       ( 0.360478, -0.301395,  0.629183, -1.440146, -0.741637, -1.19675 , -1.038444, -0.717461, b'P'),
       ( 1.563238, -1.294753,  0.078987,  1.432937,  1.149136, -1.29214 ,  1.562988, -0.937731, b'P'),
       ...,
       ( 0.103862,  1.024329, -1.047221,  0.280905, -0.181155, -0.651934, -1.241842,  1.53022 , b'N'),
       (-1.109311, -0.02769 , -1.448736, -0.648566, -0.462142,  0.814971,  1.100615,  1.337159, b'N'),
       ( 1.155011, -0.429331, -1.56726 ,  0.883077, -1.203777, -0.126506,  0.331042, -1.327384, b'P')],
      dtype=[('theta1', '<f8'), ('theta2', '<f8'), ('theta3', '<f8'), ('theta4', '<f8'), ('theta5', '<f8'), ('theta6', '<f8'), ('theta7', '<f8'), ('theta8', '<f8'), ('binaryClass', 'S1')])

In [59]:
# Na dole jest przykład jak wczytywać dane - jest klasa DataLoader jak coś
data = np.array(data.tolist(), dtype=object)
# y = np.array(data.tolist()[:, -1], dtype=object)
x = data[:, :-1].astype(float)
# y= (data[:, -1] - 1)
# x

In [26]:
from sklearn.model_selection import train_test_split

from src.model.LogisticRegression import LogisticRegression
from src.optim.IWLS import IWLS
from src.optim.SGD import SGD
from src.optim.ADAM import ADAM
from src.optim.conditions import MaxIterationCondition, NoLogLikImprovementCondition

train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.3, stratify=y, random_state=42)

model = LogisticRegression()
optim = IWLS(model, NoLogLikImprovementCondition(1))

model = optim.optimize(train_x, train_y)
balanced_accuracy_score(test_y, model.predict(test_x))

0.558765778401122

In [5]:
optim.stop_condition.epoch

38

In [6]:
model.weights

array([-0.00994713, -0.01611059,  0.00945837,  0.01735449,  0.00939425])

In [ ]:
print(model.weights)

In [7]:
model.predict(test_x)

array([0, 1, 0, ..., 0, 1, 0])

In [ ]:
raise ValueError()

In [ ]:
from sklearn.model_selection import train_test_split

from src.model.LogisticRegression import LogisticRegression
from src.optim.IWLS import IWLS
from src.optim.conditions import MaxIterationCondition

train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.3, stratify=y, random_state=42)

accs = []
for i in range(1, 20):
    model = LogisticRegression()
    optim = IWLS(model, MaxIterationCondition(i))

    model = optim.optimize(train_x, train_y)

    balanced_acc = balanced_accuracy_score(test_y, model.predict(test_x))
    accs.append(balanced_acc)


In [ ]:
import seaborn as sns
sns.lineplot(x=list(range(1,20)), y=accs)

In [24]:
from sklearn.model_selection import train_test_split
from src.model.LogisticRegression import LogisticRegression
from src.optim.IWLS import IWLS
from src.optim.SGD import SGD
from src.optim.ADAM import ADAM
from src.optim.conditions import MaxIterationCondition, NoLogLikImprovementCondition
from src.data_loader.DataLoader import DataLoader
from sklearn.metrics import balanced_accuracy_score
import warnings
warnings.filterwarnings('ignore')

# Example of usage
dl = DataLoader()
sd = dl.get_supported_datasets()
for d in sd:
    print(d)
    x, y = dl[d]
    train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.3, stratify=y, random_state=42)

    model = LogisticRegression()
    optim = ADAM(model, NoLogLikImprovementCondition(500))

    model = optim.optimize(train_x, train_y)
    print(balanced_accuracy_score(test_y, model.predict(test_x)))

    print(model.predict(test_x))

    print('---')

banknote
0.9666881427923736
[0 1 0 1 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 1 0 0 1 1 0 1 1 0 1 1
 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 0 0 1 0 1 1 0 1 0 1 0 0 1 0 0 1 1 0
 0 0 1 0 1 1 1 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 1 0 1 0 0 1 0 1 0 0 1 1 0 0 1
 1 1 0 0 0 0 0 1 0 1 0 1 0 1 1 0 0 0 1 0 1 0 0 0 0 0 1 0 1 0 0 1 0 1 0 1 0
 0 0 1 1 1 1 1 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 0 1 0 1 1 0
 1 1 0 0 1 0 1 0 1 1 1 1 1 0 0 0 0 0 1 1 1 0 1 0 1 1 0 1 0 1 0 1 1 0 0 1 1
 1 1 0 0 0 0 1 1 1 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1
 1 0 0 0 0 0 1 0 1 1 0 0 1 1 1 0 1 0 0 1 1 1 0 1 1 0 1 1 1 1 0 1 0 0 1 1 0
 0 0 0 0 0 1 0 0 1 1 0 1 0 0 0 0 0 0 1 1 1 1 1 1 0 0 1 1 0 1 1 0 0 0 1 0 1
 1 1 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 1 0 0 1
 0 0 0 0 1 0 1 1 1 1 0 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0 1 1 1 0
 0 0 1 1 1]
---
kin8nm
0.7277392667473312
[0 0 1 ... 0 0 1]
---
phoneme
0.6618985290451259
[0 0 0 ... 0 0 0]
---
elevators
0.48175340025934255
[0 1

In [11]:
dl['pc1'][1] 

array([0., 1., 1., ..., 0., 0., 0.])